name: Push to Docker.io
on:
  workflow_dispatch:
  create:
    tags:
      - .*

jobs:
  install:
    name: Build & Deploy in docker.io
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      # Production versions
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: somfyProtect2Mqtt/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            minims/somfyprotect2mqtt:latest
            minims/somfyprotect2mqtt:${{  github.ref_name }}
