name: Push to Docker.io
#on: workflow_dispatch
# Run this workflow every time a new tag is created
on:
  create:
    tags:
      - .*

jobs:
  install:
    name: Build & Deploy in docker.io
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Tag Number
        id: tag-number
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check Tag Release
        env:
          RELEASE_VERSION: ${{ steps.tag-number.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Production versions
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: somfyProtect2Mqtt/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            minims/somfyprotect2mqtt:latest
            minims/somfyprotect2mqtt:${{ steps.vars.outputs.tag }}
